### ISSUE TITLE
异步线程报错

### ISSUE THREAD

**Issue by MinchinWang** [LanSoSdk/LanSoEditor_common#58]
native: #08 pc 000bcb95  /data/app/com.serenegiant.usbcameratest4-2/lib/arm/libLanSongffmpeg.so (post_event_from_native+60)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.execute(Native method)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.executeVideoEditor(VideoEditor.java:261)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.executeWithEncoder(VideoEditor.java:3096)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.executeAutoSwitch(VideoEditor.java:3000)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.executeOverLayVideoFrame(VideoEditor.java:1737)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at com.serenegiant.service.ShuiyinServer.demoAddPicture(ShuiyinServer.java:237)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at com.serenegiant.service.ShuiyinServer$SubAsyncTask.doInBackground(ShuiyinServer.java:158)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   - locked <0x0449788c> (a com.serenegiant.service.ShuiyinServer$SubAsyncTask)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at com.serenegiant.service.ShuiyinServer$SubAsyncTask.doInBackground(ShuiyinServer.java:83)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-12 10:24:38.420 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-12 10:24:38.421 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Thread.run(Thread.java:818)
03-12 10:24:38.421 9557-9620/com.serenegiant.usbcameratest4 A/art: art/runtime/java_vm_ext.cc:410] 
03-12 10:24:38.515 9557-9619/com.serenegiant.usbcameratest4 E/HAL: Dawei load: module=/system/lib/hw/gralloc.msm8937.so

**Comment by LanSoSdk** [comment]
请只有armeabi-v7a的指令集,并不要混淆我们的SDK
