### ISSUE TITLE
打了release包后式初始化失败

### ISSUE THREAD

**Issue by apple2360541** [LanSoSdk/LanSoEditor_common#59]
Process: com.yihuan.archeryplus, PID: 7497
                                                 java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.yihuan.archeryplus-B4C7L5At8kqjt4uw_oBjTw==/lib/arm/libLanSongdisplay.so"
                                                     at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
                                                     at java.lang.System.loadLibrary(System.java:1657)
                                                     at com.lansosdk.videoeditor.LanSoEditor.loadLibraries(LanSoEditor.java:35)
                                                     at com.lansosdk.videoeditor.LanSoEditor.initSDK(LanSoEditor.java:22)

**Comment by LanSoSdk** [comment]
请不要混淆我们的SDK
