### ISSUE TITLE
请问初始化闪退原因

### ISSUE THREAD

**Issue by yaopin002** [LanSoSdk/LanSoEditor_common#66]
LanSoEditor.initSDK这里报错并闪退，请是什么原因
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.xxx.xx-T35KlRTDDqmDRL-gMqpGOQ==/base.apk"],nativeLibraryDirectories=[/data/app/cn.runningquotient.rq-T35KlRTDDqmDRL-gMqpGOQ==/lib/arm64, /data/app/cn.runningquotient.rq-T35KlRTDDqmDRL-gMqpGOQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libLanSongffmpeg.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1660)
        at com.lansosdk.videoeditor.LanSoEditor.loadLibraries(LanSoEditor.java:32)

**Comment by LanSoSdk** [comment]
免费版当前只支持 armeabi-v7a 
请在gradle中增加:
ndk{
abiFilters "armeabi-v7a"
}
