### ISSUE TITLE
并行执行多个任务时crash

### ISSUE THREAD

**Issue by willowWH** [LanSoSdk/LanSoEditor_common#91]
使用sdk中的方法并行执行多个任务时候，demo闪退

07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: thread Thread[13,tid=11982,Native,Thread*=0xabdf9b40,peer=0x12dbaf40,"AsyncTask #1"] using JNIEnv* from thread Thread[13,tid=11982,Native,Thread*=0xabdf9b40,peer=0x12dbaf40,"AsyncTask #1"]
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]     in call to CallVoidMethod
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]     from int com.lansosdk.videoeditor.VideoEditor.execute(java.lang.Object)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410] "AsyncTask #1" prio=5 tid=13 Runnable
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x12dbaf40 self=0xabdf9b40
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=11982 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0xef303930
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 250482664 20839950 336 ) utm=23 stm=2 core=1 HZ=100
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   | stack=0xef201000-0xef203000 stackSize=1038KB
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 0035c6d5  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+116)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 0033d1b7  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+138)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0024f3e1  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+760)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 0024fa7f  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+54)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 000fbdeb  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+30)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 00100c55  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.95+4940)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 0010ed7b  /system/lib/libart.so (_ZN3art8CheckJNI11CallMethodVEPKcP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDSt9__va_listNS_9Primitive4TypeENS_10InvokeTypeE+498)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 0010ff81  /system/lib/libart.so (_ZN3art8CheckJNI14CallVoidMethodEP7_JNIEnvP8_jobjectP10_jmethodIDz+40)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 000bde4d  /data/app/com.lansoeditor.demo-2/lib/arm/libLanSongffmpeg.so (post_event_from_native+60)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.execute(Native method)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.executeVideoEditor(VideoEditor.java:261)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.executeWithEncoder(VideoEditor.java:3095)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoEditor.executeAutoSwitch(VideoEditor.java:2995)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoLayout.doVideoLayout(VideoLayout.java:727)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at com.lansosdk.videoeditor.VideoLayout.executeLayout4Video(VideoLayout.java:273)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at com.example.commonDemo.VideoLayoutDemoActivity$SubAsyncTask.doInBackground(VideoLayoutDemoActivity.java:298)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   - locked <0x0eb0d279> (a com.example.commonDemo.VideoLayoutDemoActivity$SubAsyncTask)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at com.example.commonDemo.VideoLayoutDemoActivity$SubAsyncTask.doInBackground(VideoLayoutDemoActivity.java:288)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Thread.run(Thread.java:818)
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/java_vm_ext.cc:410] 
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/runtime.cc:368] Runtime aborting...
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/art: art/runtime/runtime.cc:368] 
07-04 11:13:34.109 11312-11982/com.lansoeditor.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 11982 (AsyncTask #1)
07-04 11:13:34.189 543-543/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-04 11:13:34.189 543-543/? A/DEBUG: Build fingerprint: 'samsung/a9xproltezc/a9xproltechn:6.0.1/MMB29M/A9100ZCU1AQH1:user/release-keys'
07-04 11:13:34.189 543-543/? A/DEBUG: Revision: '1'
07-04 11:13:34.189 543-543/? A/DEBUG: ABI: 'arm'
07-04 11:13:34.189 543-543/? A/DEBUG: pid: 11312, tid: 11982, name: AsyncTask #1  >>> com.lansoeditor.demo <<<
07-04 11:13:34.189 543-543/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-04 11:13:34.219 543-543/? A/DEBUG: Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: thread Thread[13,tid=11982,Native,Thread*=0xabdf9b40,peer=0x12dbaf40,"AsyncTask #1"] using JNIEnv* from thread Thread[13,tid=11982,Native,Thread*=0xabdf9b40,peer=0x12dbaf40,"AsyncTask #1"]'
07-04 11:13:34.219 543-543/? A/DEBUG:     r0 00000000  r1 00002ece  r2 00000006  r3 ef303978
07-04 11:13:34.219 543-543/? A/DEBUG:     r4 ef303980  r5 ef303930  r6 0000000b  r7 0000010c
07-04 11:13:34.219 543-543/? A/DEBUG:     r8 ef302ec1  r9 f4b88418  sl f4ba2e44  fp f4b56958
07-04 11:13:34.219 543-543/? A/DEBUG:     ip 00000006  sp ef302e18  lr f73c9f35  pc f73cc330  cpsr 40070010
07-04 11:13:34.219 543-543/? A/DEBUG: backtrace:
07-04 11:13:34.219 543-543/? A/DEBUG:     #00 pc 00044330  /system/lib/libc.so (tgkill+12)
07-04 11:13:34.219 543-543/? A/DEBUG:     #01 pc 00041f31  /system/lib/libc.so (pthread_kill+32)
07-04 11:13:34.219 543-543/? A/DEBUG:     #02 pc 0001ba33  /system/lib/libc.so (raise+10)
07-04 11:13:34.219 543-543/? A/DEBUG:     #03 pc 00018ca1  /system/lib/libc.so (__libc_android_abort+34)
07-04 11:13:34.219 543-543/? A/DEBUG:     #04 pc 00016860  /system/lib/libc.so (abort+4)
07-04 11:13:34.219 543-543/? A/DEBUG:     #05 pc 0031e295  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+200)
07-04 11:13:34.219 543-543/? A/DEBUG:     #06 pc 000f3a0d  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2212)
07-04 11:13:34.219 543-543/? A/DEBUG:     #07 pc 0024f6dd  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1524)
07-04 11:13:34.219 543-543/? A/DEBUG:     #08 pc 0024fa7f  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+54)
07-04 11:13:34.219 543-543/? A/DEBUG:     #09 pc 000fbdeb  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+30)
07-04 11:13:34.219 543-543/? A/DEBUG:     #10 pc 00100c55  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE.constprop.95+4940)
07-04 11:13:34.219 543-543/? A/DEBUG:     #11 pc 0010ed7b  /system/lib/libart.so (_ZN3art8CheckJNI11CallMethodVEPKcP7_JNIEnvP8_jobjectP7_jclassP10_jmethodIDSt9__va_listNS_9Primitive4TypeENS_10InvokeTypeE+498)
07-04 11:13:34.219 543-543/? A/DEBUG:     #12 pc 0010ff81  /system/lib/libart.so (_ZN3art8CheckJNI14CallVoidMethodEP7_JNIEnvP8_jobjectP10_jmethodIDz+40)
07-04 11:13:34.219 543-543/? A/DEBUG:     #13 pc 000bde4d  /data/app/com.lansoeditor.demo-2/lib/arm/libLanSongffmpeg.so (post_event_from_native+60)
07-04 11:13:34.589 543-543/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_03
07-04 11:13:34.589 543-543/? E/DEBUG: AM write failed: Broken pipe
07-04 11:13:34.599 2728-2728/? E/audit: type=1701 msg=audit(1562210014.589:1049): auid=4294967295 uid=10389 gid=10389 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=11982 comm=4173796E635461736B202331 reason="memory violation" sig=6

**Comment by LanSoSdk** [comment]
execute不可以两个两个方法同时执行, 因为手机只有一个硬件解码器, 并且ffmpeg用了一些全部变量. 
你两个同时执行, 就造成的ffmpeg中context公用一个,从而出错.
